name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.1

#      - name: Run golangci-lint
#        uses: golangci/golangci-lint-action@v3.7.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -timeout 120s ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Test coverage stat
        run: go test -cover -timeout 120s ./...
      - name: Cover
        run: go test -coverprofile=cover.out ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          # Hack to resolve package:
          # https://github.com/paambaati/codeclimate-action/issues/109#issuecomment-751311299
          coverageCommand: make coverage
          prefix: ${{ github.event.repository.name }}
          coverageLocations: "${{github.workspace}}/c.out:gocov"
          debug: true
