name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -timeout 120s ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Test Covarage Stat
        run: go test -cover -timeout 120s ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
